name: iconfont_builder
description: Iconfont 有 500w 个图标，而且各个公司的设计师还在源源不断的为其增加新的图标，此库仅为了更便捷的在 Flutter 中使用 Iconfont 字体图标库
version: 0.1.7
author: pillar<ymzuiku@gmail.com>
homepage: https://github.com/ymzuiku/iconfont_builder

executables:
  iconfont_builder: main

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  args: any
  lpinyin: ^1.0.7

dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
